//! Generated protobuf types for the PBv2 import protocol.
//!
//! Types are generated by `prost-build` from `proto/pbv2.proto` at build time
//! and written to `src/generated/pbv2.rs`.
//!
//! # Zenoh key space
//!
//! | Direction          | Key                      |
//! |--------------------|--------------------------|
//! | Importer → Backend | `pbv2/import/problems`   |
//! | Backend → Importer | `pbv2/import/ack`        |

include!(concat!(env!("OUT_DIR"), "/pbv2.rs"));
